### ISSUE TITLE
which jsonwebretrieve?

### ISSUE THREAD

**Issue by ever4cyth** [spidezad/google_screener_data_extract#1]
python google_screener_data_extract.py 
Traceback (most recent call last):
  File "google_screener_data_extract.py", line 27, in <module>
    from jsonwebretrieve import WebJsonRetrieval
ImportError: No module named jsonwebretrieve

not in pypi, please help.

**Comment by spidezad** [comment]
Hi ever4cyth,

Thanks for pointing it out. I have missed this module. Have uploaded it. Pls try to see if it works now.

**Comment by spidezad** [comment]
Thanks for pointing it out. I have missed this module. Have uploaded it.
Pls try to see if it works now.

Thanks very much for your feedback

**Comment by ever4cyth** [comment]
Thanks, Tan! it works great now.

I hope you don't mind asking you another question. I still didn't get how
to retrieve the full url although I read your sept poster again and again.
Could you please show me an example? I am in US and like to get NASDAQ
stock info, google finance web page
https://www.google.com/finance#stockscreener shows 3630 records. I looked
at page resource and there are something like
/finance?q=NASDAQ:PTCT&amp;ei=eKUlVoGFKMfFeoGPitAP,
view-source:https://www.google.com/finance?q=NASDAQ:PTCT&ei=eKUlVoGFKMfFeoGPitAP
but how to turn it into URL like the one in your poster?

**Comment by spidezad** [comment]
I have attached a pic detailing this. Hope it helps.

![sample](https://cloud.githubusercontent.com/assets/3501895/10625972/fa91e1b0-77dc-11e5-94f0-0b06936bc6b0.png)

**Comment by ever4cyth** [comment]
Thanks a lot for your help! I am able to make it to work with your detailed
instructions.

**Comment by spidezad** [comment]
That's great! :)

**Comment by urvashisikka** [comment]
Hi i still get the web Json Retrieval error < no module named webjsonretrieval >
